# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: daemon.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x64\x61\x65mon.proto\x12\x07metrics\x1a\x1bgoogle/protobuf/empty.proto\"V\n\rStaticMetrics\x12\x13\n\x0b\x43PUNumCores\x18\x01 \x01(\x05\x12\x0f\n\x07\x43PUName\x18\x02 \x01(\t\x12\x10\n\x08MBMemory\x18\x03 \x01(\x05\x12\r\n\x05MBRam\x18\x04 \x01(\x05\"I\n\x0e\x44ynamicMetrics\x12\x10\n\x08\x43PUUsage\x18\x01 \x01(\x05\x12\x13\n\x0bMemoryUsage\x18\x02 \x01(\x05\x12\x10\n\x08RamUsage\x18\x03 \x01(\x05\x32\x99\x01\n\x07Metrics\x12\x45\n\x11SendStaticMetrics\x12\x16.metrics.StaticMetrics\x1a\x16.google.protobuf.Empty\"\x00\x12G\n\x12SendDynamicMetrics\x12\x17.metrics.DynamicMetrics\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'daemon_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STATICMETRICS']._serialized_start=54
  _globals['_STATICMETRICS']._serialized_end=140
  _globals['_DYNAMICMETRICS']._serialized_start=142
  _globals['_DYNAMICMETRICS']._serialized_end=215
  _globals['_METRICS']._serialized_start=218
  _globals['_METRICS']._serialized_end=371
# @@protoc_insertion_point(module_scope)
