# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import user_pb2 as user__pb2


class JobStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendJob = channel.unary_unary(
                '/job.Job/SendJob',
                request_serializer=user__pb2.JobMetrics.SerializeToString,
                response_deserializer=user__pb2.HeadNode.FromString,
                )


class JobServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_JobServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendJob': grpc.unary_unary_rpc_method_handler(
                    servicer.SendJob,
                    request_deserializer=user__pb2.JobMetrics.FromString,
                    response_serializer=user__pb2.HeadNode.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'job.Job', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Job(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/job.Job/SendJob',
            user__pb2.JobMetrics.SerializeToString,
            user__pb2.HeadNode.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
